import { setDefaultOptions } from 'date-fns';
import { ru } from 'date-fns/locale';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Providers from '@/components/providers';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  setDefaultOptions({ locale: ru });
  return (
    <html lang="en">
      <body className={`${inter.className} flex min-h-screen flex-col`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
